server:
  port: 8080

spring:

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

    hibernate:
      ddl-auto: none

logging:
  level:
    kim.zhyun.tistory.client: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: refresh
