sequenceDiagram
    autonumber
    loop 전체 글 목록 velog.post에 저장
        Local -->> +Velog: 글 목록 요청 (한번에 100건)
        Velog -->> -Local: 글 목록
        Local -->> DB: velog.tag 저장
        rect rgb(111, 121, 151)
            Note over Local , DB: << table tags >><br>tag_seq, tag
        end
        Local -->> DB: velog.post 일부 field 저장
        rect rgb(111, 121, 151)
            Note over Local , DB: << table posts >><br>post_seq, post_id, url_slug, title,<br>released_at, updated_at, is_private
        end
    end


